export {default as SEO} from './seo'
export {default as Layout} from './layout'
export {default as Image} from './image'
export {default as Navb} from './navb'
export {default as Footer} from './footer'
